import { db } from "./db";
import { workers, projects, workOrders } from "@shared/schema";

export async function seedDatabase() {
  const existingProjects = await db.select().from(projects);
  if (existingProjects.length > 0) return;

  const createdWorkers = await db.insert(workers).values([
    {
      name: "Marcus Rivera",
      title: "Senior Electrician",
      trade: "Electrician",
      email: "m.rivera@flux.io",
      phone: "+1 (602) 555-0142",
      location: "Phoenix, AZ",
      experience: 14,
      certifications: ["Master Electrician", "OSHA 30", "NFPA 70E"],
      available: true,
      bio: "Specialized in high-voltage power distribution systems for Tier III and IV data centers. Led electrical teams on 12+ hyperscale builds.",
    },
    {
      name: "Sarah Chen",
      title: "HVAC Lead",
      trade: "HVAC Technician",
      email: "s.chen@flux.io",
      phone: "+1 (972) 555-0198",
      location: "Dallas, TX",
      experience: 11,
      certifications: ["EPA 608 Universal", "ASHRAE Certified", "LEED AP"],
      available: false,
      bio: "Expert in precision cooling systems and hot/cold aisle containment for high-density compute environments.",
    },
    {
      name: "James Okafor",
      title: "Project Manager",
      trade: "Project Manager",
      email: "j.okafor@flux.io",
      phone: "+1 (703) 555-0267",
      location: "Ashburn, VA",
      experience: 18,
      certifications: ["PMP", "CDCMP", "Six Sigma Black Belt"],
      available: true,
      bio: "Managed construction of 8 data centers across North America totaling over 200MW of critical IT capacity.",
    },
    {
      name: "Elena Vasquez",
      title: "Network Infrastructure Engineer",
      trade: "Network Technician",
      email: "e.vasquez@flux.io",
      phone: "+1 (503) 555-0314",
      location: "Hillsboro, OR",
      experience: 9,
      certifications: ["BICSI RCDD", "Cisco CCNP", "CDCDP"],
      available: true,
      bio: "Designs and deploys structured cabling and fiber optic infrastructure for hyperscale campus environments.",
    },
    {
      name: "Robert Kim",
      title: "Facility Engineer",
      trade: "Facility Engineer",
      email: "r.kim@flux.io",
      phone: "+1 (408) 555-0421",
      location: "Santa Clara, CA",
      experience: 15,
      certifications: ["CDCEP", "AEE CEM", "Uptime Tier Designer"],
      available: false,
      bio: "Oversees critical infrastructure operations including UPS, generators, and BMS for multi-site portfolios.",
    },
  ]).returning();

  const createdProjects = await db.insert(projects).values([
    {
      name: "Phoenix Hyperscale DC-3",
      client: "CloudPeak Technologies",
      location: "Phoenix, AZ",
      status: "active",
      description: "New 60MW hyperscale data center with advanced liquid cooling infrastructure. Tier IV design with 2N redundancy on all critical systems.",
      startDate: "2025-09-01",
      endDate: "2026-12-15",
      progress: 42,
      powerCapacity: "60MW",
      tier: "tier_4",
    },
    {
      name: "Dallas Metro Edge Campus",
      client: "NexGen Digital",
      location: "Dallas, TX",
      status: "active",
      description: "Edge computing campus with three interconnected facilities. Focus on low-latency connectivity and renewable energy integration.",
      startDate: "2025-06-15",
      endDate: "2026-08-30",
      progress: 68,
      powerCapacity: "25MW",
      tier: "tier_3",
    },
    {
      name: "Ashburn Data Hall Expansion",
      client: "Atlantic Data Systems",
      location: "Ashburn, VA",
      status: "planning",
      description: "Expansion of existing campus with two additional data halls. Includes upgraded power distribution and enhanced cooling capacity.",
      startDate: "2026-03-01",
      endDate: "2027-06-30",
      progress: 8,
      powerCapacity: "40MW",
      tier: "tier_3",
    },
    {
      name: "Hillsboro Network Hub",
      client: "Pacific Fiber Corp",
      location: "Hillsboro, OR",
      status: "completed",
      description: "High-density network interconnection facility with carrier-neutral meet-me rooms and 100G fabric throughout.",
      startDate: "2024-11-01",
      endDate: "2025-10-15",
      progress: 100,
      powerCapacity: "15MW",
      tier: "tier_3",
    },
    {
      name: "Santa Clara AI Compute Center",
      client: "Tensor Infrastructure",
      location: "Santa Clara, CA",
      status: "active",
      description: "Purpose-built facility for AI/ML workloads with direct liquid cooling to chip and 100kW+ per rack density support.",
      startDate: "2025-07-01",
      endDate: "2026-11-30",
      progress: 35,
      powerCapacity: "80MW",
      tier: "tier_4",
    },
  ]).returning();

  await db.insert(workOrders).values([
    {
      title: "Install PDU Bus Duct in Hall A",
      description: "Install and commission 4x 500A bus duct runs from main switchgear to PDU positions A1-A4.",
      projectId: createdProjects[0].id,
      assigneeId: createdWorkers[0].id,
      status: "in_progress",
      priority: "high",
      trade: "Electrical",
      dueDate: "2026-03-15",
    },
    {
      title: "Commission CRAH Units 1-8",
      description: "Complete startup and commissioning of all 8 CRAH units in Data Hall 2. Verify airflow, cooling capacity, and BMS integration.",
      projectId: createdProjects[1].id,
      assigneeId: createdWorkers[1].id,
      status: "in_progress",
      priority: "medium",
      trade: "HVAC",
      dueDate: "2026-02-28",
    },
    {
      title: "Fiber Backbone Installation",
      description: "Run single-mode fiber backbone between MDF and all IDF locations. 288-strand count with 30% spare capacity.",
      projectId: createdProjects[0].id,
      assigneeId: createdWorkers[3].id,
      status: "open",
      priority: "high",
      trade: "Networking",
      dueDate: "2026-04-01",
    },
    {
      title: "Generator Load Bank Testing",
      description: "Perform 4-hour load bank test on all 6 diesel generators at 100% rated capacity. Document fuel consumption and voltage stability.",
      projectId: createdProjects[4].id,
      assigneeId: createdWorkers[4].id,
      status: "open",
      priority: "urgent",
      trade: "Electrical",
      dueDate: "2026-02-20",
    },
    {
      title: "Fire Suppression System Inspection",
      description: "Annual inspection of clean agent fire suppression system in all server halls. Verify agent levels, detection systems, and release mechanisms.",
      projectId: createdProjects[1].id,
      status: "open",
      priority: "medium",
      trade: "Fire Protection",
      dueDate: "2026-03-10",
    },
    {
      title: "UPS Battery Replacement - Module 3",
      description: "Replace end-of-life battery strings in UPS Module 3. Coordinate with operations for planned maintenance window.",
      projectId: createdProjects[4].id,
      assigneeId: createdWorkers[0].id,
      status: "open",
      priority: "high",
      trade: "Electrical",
      dueDate: "2026-03-05",
    },
    {
      title: "Raised Floor Tile Installation",
      description: "Install 2,400 perforated floor tiles in new data hall. Ensure proper airflow management and cable routing compliance.",
      projectId: createdProjects[0].id,
      status: "completed",
      priority: "medium",
      trade: "General",
      dueDate: "2026-01-30",
    },
    {
      title: "BMS Integration for Cooling Plant",
      description: "Configure and test building management system integration with chiller plant and cooling tower controls.",
      projectId: createdProjects[1].id,
      assigneeId: createdWorkers[1].id,
      status: "completed",
      priority: "high",
      trade: "Mechanical",
      dueDate: "2026-01-15",
    },
  ]);

  console.log("Database seeded successfully with realistic data center data.");
}
